name: 🐞 Bug report
description: Create a report to help improve Clock
labels:
  - "bug"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping make Clock better!  
        Please follow these guidelines for a good bug report:
        • Search existing issues (open and closed) to avoid duplicates.  
        • Give your bug report a clear title (avoid "Error" or "Crash").  
        • Describe the bug concisely.  
        • If you have a screenshot or screen recording of the bug, link them at the end of this issue.  
        • Fill out environment information (app version, device, OS). 

  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      value: |
        1. Go to '…'
        2. Click on '…'
        3. Scroll down to '…'
        4. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs (optional but highly recommended)
      description: Attach your log files here.
      placeholder: |
        1. Notice the bug.
        2. Go to About, click 5 times on the version number.
        3. Tap the insect 🐞 icon that appears.
        4. Save the generated .zip file to your device.
        5. Attach the .zip file in your issue comment.

  - type: input
    id: appversion
    attributes:
      label: App version
      placeholder: e.g. 2.6.0 (or commit hash if self-built)
    validations:
      required: true

  - type: dropdown
    id: installsource
    attributes:
      label: Install Source
      options:
        - GitHub
        - F-Droid
        - IzzyOnDroid
        - Obtainium
        - OpenAPK
        - Other
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device model
      placeholder: e.g. Google Pixel 9 Pro
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Android version
      placeholder: e.g. Android 15 (Stock / Custom ROM)
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: "I searched for _existing issues_ ([open](https://github.com/BlackyHawky/Clock/issues) and [closed](https://github.com/BlackyHawky/Clock/issues?q=is%3Aissue%20state%3Aclosed)) before filing this report."
          required: true
        - label: "I have read and understood the [contribution guidelines](https://github.com/BlackyHawky/Clock/blob/main/CONTRIBUTING.md)."
          required: true
        - label: "I have provided all required details. I understand that the feature request will be dismissed otherwise."
          required: true
